let people = [
  {
    name: "David Luu",
    age: 25,
    gender: "Male",
    race: "Asian",
    exes: 10,
    image: "images/David Luu.jpg",
  },
  {
    name: "Travis Liu",
    age: 22,
    gender: "Male",
    race: "Asian",
    exes: 23,
    image: "images/Travis Liu.jpg",
  },
  {
    name: "Tiffiany",
    age: 19,
    gender: "Female",
    race: "Asian",
    exes: 15,
    image: "images/Tiffiany.jpg",
  },
  {
    name: "Travis",
    age: 25,
    gender: "Male",
    race: "Asian",
    exes: 7,
    image: "images/Travis Liu.jpg",
  },
  {
    name: "Erica",
    age: 20,
    gender: "Female",
    race: "Asian",
    exes: 9,
    image: "images/Erica.jpg",
  },
  {
    name: "Terrance",
    age: 23,
    gender: "Male",
    race: "Asian",
    exes: 5,
    image: "images/Terrance Wong.jpg",
  },
  {
    name: "Kevin Ngyuen",
    age: 26,
    gender: "Male",
    race: "Asian",
    exes: 12,
    image: "images/Kevin Ngyuen.jpg",
  },
  {
    name: "Rerick",
    age: 26,
    gender: "Male",
    race: "White",
    exes: 4,
    image: "images/Rerick.jpg",
  },
  {
    name: "Aang",
    age: 18,
    gender: "Male",
    race: "Asian",
    exes: 8,
    image: "images/Aang.jpg",
  },
  {
    name: "Eric Ou",
    age: 20,
    gender: "Male",
    race: "Asian",
    exes: 11,
    image: "images/Eric Ou.jpg",
  },
  {
    name: "Henry Lin",
    age: 25,
    gender: "Male",
    race: "Asian",
    exes: 6,
    image: "images/Henry Lin.jpg",
  },
  {
    name: "Jennifer",
    age: 22,
    gender: "Female",
    race: "Asian",
    exes: 3,
    image: "images/Jennifer.jpg",
  },
  {
    name: "Serena",
    age: 21,
    gender: "Female",
    race: "Asian",
    exes: 18,
    image: "images/Serena.jpg",
  },
];

export { people };
